### ISSUE TITLE
Tracker template merge creates duplicates

### ISSUE THREAD

**Issue by mppdidi** [BiglySoftware/BiglyBT#112]
Tracker template merge creates duplicates - when torrents move around tags this leads to duplicates of the exact same tracker urls.
I'm not sure if this is intentionally and tags might not be 100% suitable for workflow logic - but it would be nice to avoid this.

**Comment by parg** [comment]
merge is designed to remove duplicates  - are you sure they are exactly the same? I just tested with two tags merging the same trackers and assigned a download to both and there was no duplication

**Comment by mppdidi** [comment]
I figured that the order in what multiple tags are processed with common items leads to this situatio.
I fixed this by prefixing the tag with #(n)_tagname.
No more duplicates now.
Maybe you can comment on how tags are processed regarding their order of execution?

**Comment by parg** [comment]
Still can't see how duplicates can happen - whenever a 'merge' is performed any duplicate URLs are removed, regardless of the order of operations. 
Tag order processing isn't defined

**Comment by mppdidi** [comment]
Again - couldn't reproduce it - maybe due to crashes.
I'll close this for now.
