### ISSUE TITLE
[linux] Error message shown at startup doesn't fit to laptop screen (1366x768)

### ISSUE THREAD

**Issue by glaubersm** [BiglySoftware/BiglyBT#1640]
Every time I try to open biglyBT 2.4.0.0 on my linux distribution I get an error nessage
that is not entirely redable because it doesn't fit to my screen, Watch the screen recording please.
https://www.youtube.com/watch?v=lSCNNTvQ4-E
* OS and version neon unstable edition
* BiglyBT Version Number v2.4.0.0
* For *nix: Desktop Environment KDE Plasma 5.18.80

**Comment by TuxPaper** [comment]
Can you redownload the installer from https://github.com/BiglySoftware/BiglyBT/releases/tag/v2.4.0.0 and re-install? It will keep any config and torrents you have, but should fix the startup bug

**Comment by glaubersm** [comment]
The error message was gone.
Thank you.

**Comment by d00rsfan** [comment]
ubuntu 20.04
the same problem.
apt-get install libswt-gtk-4-java didn't resolve issue.
Reinstalled 2300 - problem gone.
so attempted to fix:
1. moved .biglybt, biglybt to backup folder,
2. downloaded GitHub_BiglyBT_Installer.sh
3. installed, started - the same error as in 1st messaged.
4. so rolled back profile and program folders to 2.3.0.0

**Comment by TuxPaper** [comment]
@d00rsfan I might know the issue with this one.

Try removing the "~/.swt" folder.  It caches swt's .so files, and it may still have the broken swt from the first install of 2.4.

**Comment by d00rsfan** [comment]
deleted .swt, biglybt; reinstalled by GitHub_BiglyBT_Installer.sh=> error gone. Thank You, @TuxPaper !
