### ISSUE TITLE
Close-down progress issue

### ISSUE THREAD

**Issue by DanielWFisher** [BiglySoftware/BiglyBT#1702]
Hi, 

Love BiglyBT. Thanks for all the amazing work. The latest version has been really buggy for me. I'm on a 2015 MacBook Pro, latest OS, and BiglyBT works fine until I go to try to shut it down. The Close-down progress box appears and most often that's where everything ends. It ties to close down forever, or about 1/3 of the time, my machine crashes. My machine doesn't have any issues with any other program and I've run several malware scans, which come up clean. When I manually stop all the torrents prior to closing the app, there isn't any problem. I did click on the Pause torrents while shutting down, but that doesn't work as the app tries to stop all the paused torrents, then it hangs. Curiously, sometimes a "Force Quit" does not cause the app to quit either. I have to do a hard shut down by holding down the power button.

Got any ideas for how to get around this?

Thanks so much!
Daniel

**Comment by parg** [comment]
That is very odd behaviour - all that is going on when the closedown dialog appears is that BiglyBT is tidily stopping all the downloads and informing trackers that activity has halted - not really any different from stopping all the torrents by hand, waiting for a bit and then closing. To cause your machine to crash (as opposed to just BiglyBT crashing or having to be force-terminated) is indicative of an OSX bug being triggered but I have no idea why the dialog would cause that. 

I can add an option to disable the dialog and revert to the older, potentially untidy closedown, do you want to try that?

**Comment by DanielWFisher** [comment]
Thank you, I thought it odd as well since the closedown operation seems so simple. What I did was do a complete uninstall and then a fresh re-install of the current version. I then started and stopped the application five or six times in a row, and have not re-encountered the issue. I'm curious if anyone else experiences the issue.  Hopefully it was just a ghost in the machine.

Thanks again!

**Comment by hectorjroman** [comment]
I reported an issue somewhat similar but in Windows. It's (closed) issue #1701 . It was solved a few hours later with an update.

**Comment by david-bakin** [comment]
By the way - I currently have ~3500 torrents sitting in the stopped state, as well as a few active ones (<50).  But the shutdown takes a long time as the dialog shows it is handling each one of the 3500.  But does it have to do that?  They were in stopped state when biglybt was started, they were in the stopped state as long as biglybt was running, and they're still in the stopped state when it is exiting.  Can they be skipped (and would it be faster?) or is something actually happening, when exiting, to these stopped torrents?

**Comment by DanielWFisher** [comment]
mine works fairly well now but sometimes still hangs, even when i stop them
all myself beforehand and have a fraction of that number of torrents.

**Comment by parg** [comment]
Might be the 'scrape stopped torrents' option - this causes state updates to stopped torrents. Currently these updates are deferred until closedown which might explain why you see everything being saved when you close - I can look at spreading these out to avoid the closedown rush.

**Comment by parg** [comment]
Try Beta B18 - see if that's any better

**Comment by david-bakin** [comment]
Something's much better.  Exit is nearly instant now. Unfortunately after I saw your initial comment I unchecked the "scrape stopped torrents" box but because I didn't see your second comment I now can't remember whether I had already upgraded to b18 _also_ when I noticed the improvement, or not; sorry!  Anyway: happy!

**Comment by pcook-gethub** [comment]
Hi! I’ve run into an issue where I exit BiglyBT, the interface closes, but the app is still running. It shows up in the Windows Task Manager and can not be killed except by a total system reboot. When trying to kill the process, windows says something about not being able to because no instance is available. If I try to restart BiglyBT, it says it can’t because another instance is running. This doesn’t always happen, but when it does, the system has been running for several days, during which BiglyBT has been closed and reopened several times.

OS and version: Windows 7 Ultimate 64 bit with JRE 8u241 
BiglyBT Version Number: 2.4.0.0

**Comment by parg** [comment]
If you can't close it with Task Manager then there is most likely some issue with Windows itself rather than BiglyBT

**Comment by pcook-gethub** [comment]
Hi! I suspect that windows may not be at fault. I didn’t get the exact message copied at the time, though  I’m sure I will get other chances to do so, but I tried both taskkill /im filename.exe /t /f and taskkill /pid processid /t /f and neither worked. If I remember right, the message given had something to do with not being able to kill the process because the parent process no longer existed.  As I indicated originally, I click the exit button on the BiglyBT interface window, it says to wait while it closes torrents and shuts down trackers and such, then the interface window disappears like normal, but the BiglyBT process is still running with no way to interact with it. After I reboot and start BiglyBT up again, there is a message saying that it did not shut down tidily.

**Comment by parg** [comment]
Surely Windows should be able to terminate any user-level process, or, if that process is locking a kernel level resource that would cause termination to leave Windows itself in an inconsistent state, at least report what that resource was. As opposed to some crap about 'parent process no longer existing'.

**Comment by pcook-gethub** [comment]
Hi! Hmmm…., an interesting response. I did some more looking on the internet and I am not the only one who has had this problem over the years. Other people, with other applications, have also experienced it, though I remembered incorrectly what the error reason said exactly. The actual reason why the process could not be terminated was because there was no running instance of the task. I would assume that this means that while BiglyBT had completed its run method, it had not finished its final shutdown processing and was somehow stuck there. The fact that after reboot and restarting BiglyBT it warned that it did not shut down tidily would seem to support this. As far as “Windows should be able to terminate any user-level process,” apparently, if a task is finished running and no errors were generated, Windows (as of Vista) will assume that the application knows what it is doing and will finish up eventually or generate an error if it can’t. Many people have expressed dismay at this behavior and believe a user should be able to kill any process they want, while others have supported it, believing that it is a programmer’s responsibility to ensure correct shutdown of their code. As to why Windows does not give further information in the error message about this non-running process, that is the mystery. Any suggestions at to what I should be looking into next?

**Comment by parg** [comment]
The problem for BiglyBT is that it runs inside the Java Virtual Machine. This container is responsible for interactions with the OS, apart from a very small 'native' component that is used to perform some OS interaction not directly provided by the Java runtime (e.g. access to the registry on Windows).

So when you say 'completed its run method' this is actually a JVM thing, not a BiglyBT thing. 

That being said, as you point out, the fact that BiglyBT complains on restart that it didn't close tidily indicates that something is still running in BiglyBT land when the process is in this state. One of the last things BiglyBT does during closedown is write a 'clean' marker to a config file, if this marker is missing on startup then the untidy close message is generated. So either it never got to write the marker, it wrote the marker but it wasn't persisted or something overwrote the marker (possibly an attempt to restart BiglyBT while the old instance isn't dead)...

I don't really know what to suggest to diagnose it further :(

**Comment by pcook-gethub** [comment]
Hi again! I have done further research, and when Windows says that the process could not be terminated because there was no running instance of the task, what it means is that the process is dead, but there are either threads belonging to the process that are still alive, and/or that there are open handles on the process that keep cleanup from completing. Any live threads are most likely blocked inside kernel code. The recommendation was to use Process Explorer to look for active threads and see where they are executing and check for open handles and to whom they belong. I will do so when next this happens.

As far as BiglyBT running inside the Java Virtual Machine, in Windows, the Java Virtual Machine uses native threads, not green threads, and therefor Windows sees and manages them. I have used Process Explorer to look at BiglyBT and a little java app of my own, and have seen the threads and the dlls in which they are executing.

**Comment by as-muncher** [comment]
The other thing with BiglyBT shutting down, is that it takes so long!  It definitely goes faster if I put my computer into airplane mode, but I'm wondering why BiglyBT doesn't do this automatically, when you choose to shut down.  It tries to shut down I2P, and while it's trying to do that, it's sucking down data for the other torrents big time, and then with a heavily-fragmented, and also encrypted hard drive, data is being written and read, and then BiglyBT is trying to shut down, and because data can still be coming and going, it takes a long time to shut down the I2P plugin and stop all the other torrents.  I'm not sure if you wanted me to post a new issue or just use this one.  It's kind of related.
