### ISSUE TITLE
Speed drops when torrent goes from downloading to seeding, and using move to different folder after download

### ISSUE THREAD

**Issue by TheBestPessimist** [BiglySoftware/BiglyBT#1811]
I download to `C:/torrentz-temp` (ssd), then on completion the torrents are moved to `D:/torrentz` (hdd). I also have enabled the option to do a check after download.

![image](https://user-images.githubusercontent.com/4482210/94938005-fc767200-04d8-11eb-8876-b7a7f74cfbf2.png)

Each time a torrent finishes download the speed of all downloading and seeding torrents drops. This can be seen in the screenshots.

torrent N finishes
![image](https://user-images.githubusercontent.com/4482210/94937503-562a6c80-04d8-11eb-80e5-62c57d2f1bc9.png)

torrent N+1 finishes 
![image](https://user-images.githubusercontent.com/4482210/94938521-976f4c00-04d9-11eb-84a9-50f144304a7b.png)

torrent N+2 finishes
![image](https://user-images.githubusercontent.com/4482210/94939750-3a749580-04db-11eb-9a3b-dfffa6e2e78e.png)

In picture 2, you can also see the speed drop from the previous torrent, and how in between torrent finishes everything is smooth and no "brutal" speed changes are noticed.

------

Java 15 (64 bit)
  Oracle Corporation
c:\program files\java

SWT v4930r7, win32, zoom=100, dpi=96
Windows 10 v10.0, amd64 (64 bit)
B2.5.0.1_B09/4 az3

**Comment by parg** [comment]
Probably your file system is 100% busy with moving the completed file and stalls IO from the running torrents. 

You could try enabling the 'copy and delete' option under Options->Files->Completion Moving

**Comment by TheBestPessimist** [comment]
> Probably your file system is 100% busy with moving the completed file and stalls IO from the running torrents.


This doesn't make sense though. My downloads go to `C:/torrentz-temp` which is the 1TB SSD. After completion they are moved to `D:/torrentz` which is the 5TB HDD (I apologise I forgot writing "(HDD)" in OP).
So even if the HDD is at 100% utilisation, the ssd is barely breaking a sweat, so the downloads should not stop or slow down at all.

Is there something i could check to get further insight into what's going on?

**Comment by parg** [comment]
Not sure if that option will help to be honest.

So what probably happens is you are seeding a file as it is moving - during the time it takes to move peer requests for the file can't be satisfied (it is half-way between two drives) so they start queueing. This backs things up and interferes with other in-progress downloads.

If you stopped the download and then moved it then perhaps that wouldn't occur.

**Comment by TheBestPessimist** [comment]
> If you stopped the download and then moved it then perhaps that wouldn't occur.


 
Could I "script" this somehow, to test if it works?
If I'm successful, I think this should be integrated into BBT, since I'm using the standard BBT settings.

**Comment by parg** [comment]
You can using a combination of Tags although it would take a bit of effort

1) don't use the global 'move on complete' (i.e. disable it), rather create a Tag, say 'T1', with a constraint of 'isComplete()' and set its 'execute on assign' action to 'Stop' the download

2) create another Tag, say 'T2',  with a constraint of 'hasTagAge( "T1" ) > 30' - this will cause the stopped downloads assigned to T1 to be assigned to T2 30 seconds later - set its 'Move On Complete' folder to be wherever you want it moved to

3) create another Tag, say 'T3', with constraint of 'hasTagAge( "T2" ) > 120' - 2 minutes after the download is assigned to T2 it will be assigned to T3 - set its 'Execute On Assign' action to 'Start' to restart the download.

Note that I haven't tested this!

Also note that if you set these up then all your existing complete downloads will be put through the cycle, probably not what you want. To avoid this you would need to create another tag, say 'T0', with a constraint of '!isComplete()' and a constraint scope of 'Addition Only' - this means that incomplete downloads will be auto-added to the Tag but not auto-removed when they complete. You would then modify the constraint of T1 to be 'hasTag( "T0" ) && isComplete()'

Kind of complicated I know...

**Comment by parg** [comment]
( See https://github.com/BiglySoftware/BiglyBT/wiki/Tags for some details )

**Comment by TheBestPessimist** [comment]
I will try to implement this _sometime_, but honestly I would much rather test this on a BBT portable installation as i don't wanna destroy my current setup.

Unfortunately, after reading the wiki BBT Portable seems rather difficult to achieve.

**Comment by parg** [comment]
I was thinking on this some more - I couldn't find a straight forward way of removing the interaction between downloads without stopping the torrent before performing the move - for example the file cache in BiglyBT is such that a write from torrent A can require a flush to torrent B which, if B is currently stuck in the middle of a file move, blocks torrent A's operation. Downloads don't have separate scheduling threads (otherwise running 1000 downloads would cause issues).

Stopping a torrent obviously drops all peer connections, when you complete a download you probably want to continue seeding to the peers you've been downloading from. Also by default there is a 'recheck pieces on completion' setting which continues in a low resource mode after the transition to seeding. Stopping the torrent interfers with this.

If there was a simple way to 'fix' this then I would do so but I've spend a few hours messing about and have failed to find it.

**Comment by parg** [comment]
I'll add an explicit cache flush prior to starting a file-move, that will at least remove one source of interaction

**Comment by parg** [comment]
Try beta B12 - I've fixed a few things that should help

**Comment by TheBestPessimist** [comment]
I did not manage to test this yet @parg. I will most likely get back to my pc and retest somewhere in December.

If anything weird is still happening, i will comment again to reopen/create a new issue.

**Comment by parg** [comment]
Thanks!

**Comment by TheBestPessimist** [comment]
Tested with 3 torrents:

after each torrent is finished, and moving from SSD (temp-download location) to HDD (final location), the download speed does not drop anymore, only the upload speed which makes sense as the HDD has limited IOPS.

Thank you Parg!

**Comment by parg** [comment]
yay!

**Comment by TheBestPessimist** [comment]
Bumping this, because it seems to be happening again:
![download speed dropped again when torrent started moving](https://user-images.githubusercontent.com/4482210/103158235-457e4f80-47c4-11eb-916b-9abaca978396.png)

Can i enable any logs to share with u?

**Comment by parg** [comment]
Interesting that it isn't completely flat-lined during the move - means that the process isn't entirely blocked.

You could try grabbing some diagnostics (Help menu, last option) when experiencing this move+download speed drop, the thread dump included in the debug info might give some clue as to where things are gumming up

**Comment by TheBestPessimist** [comment]
Here's the debug info, along with a flight recording while a movement happens

https://drive.google.com/open?id=1zInQ7CgQvWTWlNJMS98CUOAEhOxWc_7K&authuser=cristian%40tbp.land&usp=drive_fs

**Comment by parg** [comment]
Thanks for that! Looking at the thread state I don't see anything blocking execution, I see one thread doing the move operation:

    PEC:DE: Runnable, 16718ms CPU, B/W: 39/203
        java.base@15/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        java.base@15/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:68)
        java.base@15/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
        java.base@15/sun.nio.ch.IOUtil.write(IOUtil.java:58)
        java.base@15/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:285)
        app//com.biglybt.core.util.FileUtil.reallyCopyFile(FileUtil.java:2148)
        app//com.biglybt.core.util.FileUtil.renameFileSupport(FileUtil.java:2024)

and two other threads servicing read operations 

    DiskAccessController:dispatch(core/read)[0/0]: Runnable, 848453ms CPU, B/W: 1618/93805
        java.base@15/sun.nio.ch.FileDispatcherImpl.readv0(Native Method)
        java.base@15/sun.nio.ch.FileDispatcherImpl.readv(FileDispatcherImpl.java:64)
        java.base@15/sun.nio.ch.IOUtil.read(IOUtil.java:346)
        java.base@15/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:258)

       DiskAccessController:dispatch(core/read)[1/0]: Runnable, 386203ms CPU, B/W: 3056/712025
        java.base@15/sun.nio.ch.FileDispatcherImpl.readv0(Native Method)
        java.base@15/sun.nio.ch.FileDispatcherImpl.readv(FileDispatcherImpl.java:64)
        java.base@15/sun.nio.ch.IOUtil.read(IOUtil.java:346)
        java.base@15/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:258)
   
So it seems that the bottleneck is somewhere in the JVM / OS rather than something BiglyBT is doing.

Previously I fixed issues around one file operation locking another within BiglyBT but here I can't see anything to fix :(

**Comment by parg** [comment]
Is the upload being lost from the downloads that are in the 'seeding and checking' state? If so you could experiment by disabling the 'piece recheck on completion' option to see if the recheck is causing the interference.

**Comment by TheBestPessimist** [comment]
> Is the upload being lost from the downloads that are in the 'seeding and checking' state?

I dont understand what you mean here. I'm not concerned about uploads.

Anyway, in my [printscreen above](https://github.com/BiglySoftware/BiglyBT/issues/1811#issuecomment-751390021), when i highlighted the 2 `Checking; seeding` torrents, I meant to show that after the movement of torrents is completed, the speed (up and down respectively) go back to normal. 
So this speed decrease happens at the same time where the torrent movement happens, and not afterwards/before.


> to see if the recheck is causing the interference

Although i don't think this is the problem, I want to test everything. 
I see 2 options here, should I disable both?
![image](https://user-images.githubusercontent.com/4482210/103174077-d3f7dd00-4867-11eb-84db-d02d8f12a482.png)

**Comment by parg** [comment]
yah, sorry, download speed, I was getting confused... 

The setting I was refering to was "Re-check pieces when download is done"

You have 3 downloads in the act of complete checks, one active the other two queued, and there are 274 requests queued for reading (for either upload or rechecking).

There are no requests queued for writing.

So I was wondering if somehow the read activity was to blame.

**Comment by TheBestPessimist** [comment]
unticked. now trying to create a new test case.

**Comment by parg** [comment]
Another thing you could try - when the file-move starts and download speed has dropped, go to the Disk Operations view and pause the file-move (right-click+pause) - see if that causes the download speed to return to normal. Then resume the move and see if it goes down again.

**Comment by TheBestPessimist** [comment]
Something really weird is happening with my BBT installation: 
![image](https://user-images.githubusercontent.com/4482210/103178534-411d6980-488c-11eb-984b-cdad222ebea4.png)

**Comment by parg** [comment]
OK, it was worth a try :( 

I'll take a look at that blank Disk Operations view, it is vaguely possible that it has never populated properly for a 'move on complete' move operation (as opposed to a manual move operation) - I'll get on it tomorrow.

Thanks for the help so far!

**Comment by TheBestPessimist** [comment]
Maybe my BBT settings are wrong, or some other weird shit is happening, because I can barely seed from my laptop to my server. (in the same lan)
- laptop has qBittorrent as seed
- server has BBT and qBittorrent as leech
	- BBT barely downloads
	- qBT downloads with my full lan speed (70MBPS)

BBT (at least mine) has some issues here...

![image](https://user-images.githubusercontent.com/4482210/103179381-23ec9900-4894-11eb-9314-3253f0c75713.png)


-----

Second issue:
When a torrent is moved (ie from SSD to HDD), if i stop the torrent (from Library view), the move action is not stopped/paused. Instead the torrent is in state "pausing" or "stopping" until the move is finished, and only afterwards it is finally "paused"/"stopped".

**Comment by TheBestPessimist** [comment]
note: if it helps you, we can chat via BBT Chat. i am TheBestPessimist there as well

**Comment by parg** [comment]
Second issue is by design

**Comment by TheBestPessimist** [comment]
so the disk view [suggested here](https://github.com/BiglySoftware/BiglyBT/issues/1811#issuecomment-751495091) does some other magics.

**Comment by parg** [comment]
Right, the disk view allows you to cancel the 'move' operation explicitly. Or it would if there was an entry for the operation there...

**Comment by parg** [comment]
Meh, my mistake - the Disk Ops view doesn't yet have support for move-on-complete operations, just manually invoked 'move data files' on a stopped download. Sorry about that, something for me to look at...
