### ISSUE TITLE
Stuck context menu command when left-click

### ISSUE THREAD

**Issue by Xuchilbara** [BiglySoftware/BiglyBT#465]
I noticed something weird happening with the context menu that shows when one right-clicks a torrent. If one does a left-click to any option, but without releasing the button, the option gets selected, and the highlight doesn't change positions even if one moves the mouse (as it happens in Windows and basically everywhere else).

So if one clicks the wrong command, the only option to avoid executing it is to push the Esc key before relasing the button. Cost me some fails to realize this.

It would be nice to be able to change the highlight even with the left click pushed, to select the actually desired command.

Thanks.

Windows 7 Ultimate X63 SP1.
BiglyBT 1.5.0.1_B04 and many of the previous.
Desktop Environment.

**Comment by ferdnyc** [comment]
I can't reproduce, in Linux with non-Fancy Menus. If I right-click a Torrent, then hover over "Show File", hold down the left mouse button, and move the mouse up and down while continuing to hold the LMB, the highlight follows my pointer, same as if I wasn't holding the button. It doesn't stay on "Show File", and "Show File" isn't activated when I release the button unless the pointer is still hovering over "Show File".

**Comment by Xuchilbara** [comment]
Hi, ferdnyc, thanks for the reply.
I can't say if I'm using the fancy menus (I searched it, but I can't find the option), but I think I do.
It's been like this for many months for me, and I've seen it in different computers. It's not like some Java/Windows bug or something...

**Comment by ferdnyc** [comment]
Mmm, I enabled "Show Fancy Menu" (It's a the bottom of the Library (second) section of Interface > Tables in the Options), and now I do indeed see the same issue. So it's a bug in the Fancy Menu implementation, specifically.

**Comment by parg** [comment]
It was fixed to at least not select the option if you left click and then move away from the option

**Comment by Xuchilbara** [comment]
Yes, I noticed that. It still gets frozen, but at least the stuck option isn't executed unless the cursor is above it.

**Comment by ferdnyc** [comment]
> It was fixed to at least not select the option if you left click and then move away from the option

Really? Is that fix in 1.5.0.0, or did it get added after? I thought I tried it in 1.5.0.0 and it still executed, but maybe I'm misremembering. I'll check that again later.

**Comment by ferdnyc** [comment]
Ah, but I see that in BiglyBT 1.5.0.1_B12, the behavior is indeed as @parg describes: A menu selection will only execute if the LMB is **released** while the pointer is still over that entry in the menu. :+1:
