### ISSUE TITLE
Quick rename of file does not respect only a difference in letter case

### ISSUE THREAD

**Issue by david-bakin** [BiglySoftware/BiglyBT#911]
Suppose when adding a torrent you use Quick Rename to rename a file in the torrent.  And suppose you change only the case of some letters in the filename.  E.g., you change `abc.txt` to `ABC.txt`.  Turns out in this situation that even though the BiglyBT UI accepts it and from then on displays the filename as `ABC.txt` lo and behold when it actually creates the file on disk it uses the _original_ name `abc.txt`.

(BiglyBT 1.8.0.1_B25 on Windows Server 2016, NTFS file system)

**Comment by parg** [comment]
Should be fixed next beta, thanks

**Comment by david-bakin** [comment]
This bug came back a little while ago.

**Comment by Sauron3019** [comment]
The same bug exists in batch renaming and creating files.

**Comment by david-bakin** [comment]
It's also come back for quick rename quite some time ago ... oh well

**Comment by parg** [comment]
Batch rename appears to be broken, quick rename still works OK for me on Windows

**Comment by parg** [comment]
I've fixed an issue with batch rename - when you say 'The same bug exists in batch renaming and creating files' is there a separate issue with 'creating files' ?

**Comment by Sauron3019** [comment]
This bug occurs if the files are renamed before they are created.

**Comment by parg** [comment]
Fixed a bug in this area, hopefully that's the one you're seeing. Fix will be in beta B36

**Comment by Sauron3019** [comment]
Thanks for the fixes.

The bug I said still exists.
If file name is changed before the file are created, the original name is used in the created file.

![BiglyBT](https://user-images.githubusercontent.com/66399617/93402576-cd7fbf80-f88d-11ea-8a67-c111b8117029.png)

The first file in the image was renamed before it was created.
The third file in the image was renamed after it was created.

**Comment by parg** [comment]
Can you go through the exact steps used to reproduce this? For example:

Change name in Open Torrent Options dialog

or

Add a download in a 'stopped' state, rename files, then start it.

or ...

**Comment by parg** [comment]
OK, weird, I reproduced it - let me look again!

**Comment by parg** [comment]
fixed (again :) in next beta (will be B37 when built)
